### ISSUE TITLE
Frequent crashes when switching dimensions

### ISSUE THREAD

**Issue by lumiscosity** [sleepingdragoninn/surveyor#13]
See title. Briefly analyzing the logs, it seems like there's an issue with the player not being detected; probably a race condition.
https://mclo.gs/Yn0yTmh

**Comment by sleepingdragoninn** [comment]
I'm struggling to reproduce this - how exactly were you switching dimensions?

**Comment by sleepingdragoninn** [comment]
This could've been caused by changing landmarks and then swapping dimensions due to the other bug - sing out if it still happens on 22
