### ISSUE TITLE
Crash when trying to join a world after deleting an instance

### ISSUE THREAD

**Issue by iacuobos** [sleepingdragoninn/surveyor#16]
[crash-2024-04-27_17.29.57-client.txt](https://github.com/sisby-folk/surveyor/files/15140355/crash-2024-04-27_17.29.57-client.txt)

**Comment by sleepingdragoninn** [comment]
Crash fix done up as https://modrinth.com/mod/surveyor/version/0.3.3+1.20, but i'll need you to check if, when you do this, the resulting atlas map has holes in it until you rejoin the game - that might be a comorbid bug we'll need to fix as well.

**Comment by iacuobos** [comment]
Seems to be fixed! Haven't crashed recently at least.
