### ISSUE TITLE
Slow loading/saving with an existing save.

### ISSUE THREAD

**Issue by DefaultFont** [sleepingdragoninn/surveyor#23]
I've been trying to use Antique Atlas, and thus Surveyor, for a modpack for me and a few friends, but it seems to cause a reoccurring problem for us when trying to play. There are no problems on the server side of things, but it's been causing some serious issues on the client-side. When loading a singleplayer world or joining my server for the first time, it behaves normally, but upon joining for a second time or more it will frequently cause a severe delay in loading in. When trying to connect to a server in particular, it's been a frequent occurrence for me and my friends to end up disconnected while trying to join over and over again from being timed out while loading in. (given we don't crash).

It seems to always get stuck on the same part in the logs, which is when Surveyor attempts to load data for the overworld, which I've attached images of it getting stuck loading when it tries to load overworld data, then another where it successfully loads after taking a minute and 33 seconds to do. I've additionally attached an image which showcases the size of the map on the server, as well as the relevant chunk count size for a general reference to the size of the map it was loading.

I am unaware if this is an Antique Atlas issue or a Surveyor issue, but I've put the issue here since the logs said Surveyor where the issue is occurring.

![image](https://github.com/sisby-folk/antique-atlas/assets/172096448/1c1dd881-54aa-43cd-bc03-b70746c2aacb)
![image](https://github.com/sisby-folk/surveyor/assets/172096448/9b4539f7-37bc-4722-aa43-6ddb70bbe3cc)
![image](https://github.com/sisby-folk/surveyor/assets/172096448/725ddabd-cd97-43bf-993f-2cec85fe0aea)

**Comment by sleepingdragoninn** [comment]
Definitely surveyor! we heavily optimised surveyor in all the sensible places *except* saving and loading - we used spark for all the other stuff, and we're genuinely unsure how to get a detailed enough profile during the load/save part of the game to be useful.

**Comment by sleepingdragoninn** [comment]
Just realized we can profile this by loading into the nether, starting a spark profile, then moving into a large overworld. Going to try that out and see if we can improve the perf.

**Comment by k2helix** [comment]
This also happens in a server with my friends. They're on Windows and the game crashes for them. However, I'm on Linux and it is stuck in Joining world.

It started happening after some people had to copy the data folder, remove it as a mod pack update would overwrite it, and paste it again. But maybe it has nothing to do with that.

**Comment by ViciousBadger** [comment]
I have the same issue when using Antique Atlas on a dedicated server, after exploring a very large area, joining the server takes _forever_, as in several minutes on a very powerful CPU.. actually it seems like the processor is not really being used much.

**Comment by sleepingdragoninn** [comment]
So I think we're actually full of shit here - i generated about 50mb of surveyor data or a 3k chunky radius and found that loads and saves were still acceptably snappy - even with terrain/etc forced on. about 1s worth of loading NBT off disk, which makes sense.

Add atlas, and it hangs on load. So, I open the profiler, and lo and behold:
![image](https://github.com/user-attachments/assets/050057d9-d9eb-4e2d-9744-238de701a213)

**Comment by DefaultFont** [comment]
The horizon isn't hopeless, PROGRESS IS INEVITABLE. 👍 

Thank you for your hard work on this issue, Sisby, I know it's probably been a massive headache over the past months. (Also merry Christmas!)

**Comment by sleepingdragoninn** [comment]
oh right yeah, this is fixed in atlas 2.10.1 - cheers!
