### ISSUE TITLE
Modded structure in The End exceeding 1MB packet limit

### ISSUE THREAD

**Issue by ItzLucaGER** [sleepingdragoninn/surveyor#25]
Some players were exploring the end on my modded minecraft server and the server crashed. I think it is an issue with surveyor.
https://mclo.gs/u6BAdqd

surveyor version 0.5.0

**Comment by ItzLucaGER** [comment]
Turns out now it crashes as soon as you enter the end. I will try resetting the end

**Comment by ItzLucaGER** [comment]
Resetting the end fixed the issue but Im still not sure what caused it

**Comment by ItzLucaGER** [comment]
Nevermind, crash occours again. Its one of the betterEnd biomes causing it. I got a clip from one of the players
https://outplayed.tv/media/wB5BD6

**Comment by sleepingdragoninn** [comment]
Yep so you have a modded structure that's over 1MB in size. betterend makes sense for that - I'll set you up with a version that tattles on what the specific structure is, and skips sending it instead of crashing.

**Comment by ItzLucaGER** [comment]
That'd be great, I just disabled the end for now since I don't know what the specific structure is. There are a few other mods on the server that add more structures to the end.

**Comment by sleepingdragoninn** [comment]
@ItzLucaGER forgot to update on this one - we've implemented the soft failure, so try this one out again to find out who's got such a large structure & whether we can do any more workarounds.

**Comment by ItzLucaGER** [comment]
Will do

**Comment by sleepingdragoninn** [comment]
Going to close this one seeing as the soft fail is implemented - feel free to find out what the large structure is anyway!
