### ISSUE TITLE
Surveyor commands don't appear when surveyor isn't installed on the server

### ISSUE THREAD

**Issue by FaultyFunctions** [sleepingdragoninn/surveyor#29]
Hello! I'm using 1.21 with surveyor version 0.5.3+1.21. For some reason in multiplayer the surveyor commands do not work for me. This is on a purpur server. Is it just disabled in multiplayer? Or is it something wrong with my server setup?

**Comment by sleepingdragoninn** [comment]
1.21 debug:

![image](https://github.com/sisby-folk/surveyor/assets/55819817/06010c99-8c11-4081-b92d-4a7f04151010)

Can you post your logs/latest.log from the server to mclo.gs?

**Comment by FaultyFunctions** [comment]
Sure here you go:

https://mclo.gs/Jyam7Cz

The server is running Purpur 1.20.4, but our modpack is 1.21 and we use viaversion to connect our modpack to the server until we can update the server to 1.21. I'm not sure if that would cause the command to not be recognized though. These logs are with every plugin removed except for viaversion (and some datapacks).

**Comment by FaultyFunctions** [comment]
Just tested Surveyor 0.5.6+1.21 and it still doesn't work on multiplayer unfortunately.

**Comment by sleepingdragoninn** [comment]
Ah, I see the confusion - surveyor map sharing is a feature of surveyor that exists when the mod is installed on the server. 

Maps are never actually shared client->client, the sharing feature actually purely shares maps from the server->client in a facsimile.

For map sharing, you'll need to use a fabric server, and ergo a matching MC version.

**Comment by FaultyFunctions** [comment]
Ah okay makes sense, thanks for the clarification! I guess naturally I am wondering if there could be a possibility to have a paper implementation to move data between clients in the future? Similar to the fabric mod Ping Wheel, they have a paper plugin that sends the appropriate data from the paper server to player's clients. Thanks again!

Here is the mod: https://github.com/LukenSkyne/Minecraft-Ping-Wheel
and plugin:  https://github.com/RXJpaw/Minecraft-Ping-Wheel-Plugin/

**Comment by sleepingdragoninn** [comment]
Unlikely! the mod is built with server-authoritative maps in mind - and map data is extremely heavy compared to "ping of type by player at location"
