### ISSUE TITLE
 [Bug] Create Copycats and Surveyor based Antique Atlas 4 partial incompatibility

### ISSUE THREAD

**Issue by Penty2** [sleepingdragoninn/surveyor#36]
Game crashes upon first entering other dimension when both mods are installed.

Create Copycats version 1.3.8
Antique Atlas 4 version 2.9.11
 - Create new world.
 - Create Nether portal and enter it.

Minecraft Version: 1.20.1
Mod Loader: NeoForge https://mclo.gs/vxVV2J1, Fabric https://mclo.gs/A8N95Dt

According to Copycat's dev the issue is within surveyor. https://github.com/copycats-plus/copycats/issues/90

**Comment by Penty2** [comment]
Same exact crash happens with Create Big Contraptions

**Comment by sleepingdragoninn** [comment]
this is fixed in surveyor 0.6.11! antique atlas just hasn't bumped for it yet (i'll do that today) - you can just install it manually, it'll work.
