### ISSUE TITLE
Crash with ChoiceTheorem's Overhauled Village

### ISSUE THREAD

**Issue by Rage-GitHub** [sleepingdragoninn/surveyor#37]
This may be more direct to Surveyor itself, but I have also posted this on Antique Atlas 4's [repo](https://github.com/sisby-folk/antique-atlas/issues/165). But the issue seems to be with the mod generating structure landmarks of some sort, as when I get near villages, the server crashes.

[crash-2024-07-12_01.33.01-server.txt](https://github.com/user-attachments/files/16189090/crash-2024-07-12_01.33.01-server.txt)

**Comment by juanjogv** [comment]
Question, for some reason you got [ChoiceTheorem's Overhauled Village](https://modrinth.com/mod/ct-overhaul-village/version/3.4.5) mod? this exactly was happening to me, but then i removed that mod go to a vanilla village and all works like a charm.

**Comment by Rage-GitHub** [comment]
> Question, for some reason you got [ChoiceTheorem's Overhauled Village](https://modrinth.com/mod/ct-overhaul-village/version/3.4.5) mod? this exactly was happening to me, but then i removed that mod go to a vanilla village and all works like a charm.

That likely is the culprit. The issue only happens upon nearing a CTOV village, so some compatibility patch will likely need to be made for it.

**Comment by sleepingdragoninn** [comment]
this is https://github.com/sisby-folk/antique-atlas/issues/141 again, which we thought we'd patched - basically they're setting really weird values for their structure type, but I can't figure out exactly what. I'll try actually installing the mod to see.

**Comment by sleepingdragoninn** [comment]
reproduced. https://mclo.gs/FvOcZgx
![image](https://github.com/user-attachments/assets/1fe3c6ad-7a39-4eb2-8b2a-de5ee03e5cf5)

**Comment by sleepingdragoninn** [comment]
fixed in surveyor 0.6.17
