### ISSUE TITLE
World crashing when entering the nether for the first time

### ISSUE THREAD

**Issue by DaPuffer** [sleepingdragoninn/surveyor#38]
Forge,1.20.1,sinytra connector, Map atlases 4 latest version.
[latest.log](https://github.com/user-attachments/files/16194643/latest.log)
After the world crashing,first,the entire screen becomes grey,then it displays a message saying "Server closed." and sends me to the server list.
I have seen a similiar issue(https://github.com/sisby-folk/surveyor/issues/36#issue-2403576545) but it seems that it's related to copycats plus,which i don't have in my mod list.
If you re-enter the nether portal,all nether_portal blocks beside one disappear.
![image](https://github.com/user-attachments/assets/cd08bca5-c485-4080-b155-6660b2b3c3f5)

**Comment by sleepingdragoninn** [comment]
this is fixed in surveyor 0.6.11! antique atlas just hasn't bumped for it yet (i'll do that today) - you can just install it manually, it'll work.
