### ISSUE TITLE
Death screen mixin seemingly broken (kick) on 1.21

### ISSUE THREAD

**Issue by drakosoldier298** [sleepingdragoninn/surveyor#49]
game log https://mclo.gs/gVR390N
netowrk protocol error https://mclo.gs/NFfALRj

**Comment by sleepingdragoninn** [comment]
can you check if this happens on a clean instance with just surveyor?

**Comment by drakosoldier298** [comment]
Finally got around to testing *just* surveryor on a client
https://mclo.gs/FNf9H7k game log for comparison - Doesnt have any issues.
https://mclo.gs/W1obphj - adding antique atlas 4  ontop of it. DOES have the issue.

edited because i somehow uploaded the same log twice.

**Comment by sleepingdragoninn** [comment]
can't seem to reproduce this one even with .24 (before a crash safety was added to the death mixin) - closing here.
