### ISSUE TITLE
Surveyor not finding Connector

### ISSUE THREAD

**Issue by EugeneLeclerc** [sleepingdragoninn/surveyor#50]
Hi! 

I'm trying to install Surveyor on my 1.21.1 Neoforged server (to use Antique Atlas on the clients). 

With Connector (connector-2.0.0-beta.2+1.21.1-full) and FFAPI (forgified-fabric-api-0.102.0+2.0.12+1.21.1) installed, my server start correctly: [latest.log](https://github.com/user-attachments/files/16922373/latest.log)

When I add Surveyor (surveyor-0.6.23+1.21), I get an error saying it did not find Connector: [surveyor.log](https://github.com/user-attachments/files/16922375/surveyor.log)

I dont understand why. Connector seems to be correctly detected (as seen in the first log file) and Surveyor does not specify an exact version. 

I'm posting here because I guess it's on Surveyor's side, but I can ask for help on Connector's Discord if needed.

**Comment by sleepingdragoninn** [comment]
connector bug, I've had it before - it's an odd one too - feel free to search on their issues.

**Comment by unilock** [comment]
For context, this is probably the issue the Sisby folk are referencing: https://github.com/Sinytra/Connector/issues/1398
