### ISSUE TITLE
BlockPalette OOB crash on server near Terralith Amethyst Rainforest biome

### ISSUE THREAD

**Issue by HotelCalifornia** [sleepingdragoninn/surveyor#52]
I've looked at #46 and my own modpack git history and to my knowledge this crash occurred after generating a new world following a big refactor of the mods, so uninstalling a mod that added blocks after initial worldgen doesn't seem to be related to the crash for me.

The crash is pretty reproducible---when a player loads into the world near the affected chunk(s), the server crashes. I've attached a couple of crashlogs and snapshots of the world in question to this issue:

- [crash-2024-09-30_21.34.44-server.txt](https://github.com/user-attachments/files/17250044/crash-2024-09-30_21.34.44-server.txt): the initially observed crash, or close enough to it. The only thing that changed between the first instance of this crash and this one is that I had the other player on my server stay logged out, and then teleported myself nearby the chunk called out in the logs. Sure enough, the server crashed with the same error.
- [world snapshot 1](https://mega.nz/file/5hsxGDaY#j45pzfMlsWzlmyH_z_Mzj8mmpXz2EDvRPIngWXfn62g): a snapshot of the world associated with the first crash report. Notice that the chunk(s) called out in the report are not generated. My guess is that this is because surveyor was crashing the chunk loading lifecycle event and preventing them from generating/saving altogether.
- [crash-2024-10-03_16.29.18-server.txt](https://github.com/user-attachments/files/17250068/crash-2024-10-03_16.29.18-server.txt): This is a crash report from today, after doing a bit of investigation. I disabled antique atlas 4 and surveyor, loaded into the world to generate the chunks in question, logged out and re-enabled the mods, then logged back in. Seeing the same crash, but multiple chunks are called out. Digging through the world files, it looks like the affected chunks correspond almost exactly to the terralith:amethyst_rainforest biome on the surface.
- [world snapshot 2](https://mega.nz/file/Ms9zQDwL#q-96lHvREh2ismOaHy5QOKrY2tGiLgL-I6B1amWldDQ): a snapshot of the world associated with the second crash report

![image](https://github.com/user-attachments/assets/141d1145-8118-45ad-a3da-164ac895e396)
This is a screenshot of MCA Selector with the two world snapshots side-by-side. On the right is the first world snapshot, after the initial crashes and before I logged in without surveyor & co to generate the chunks. On the left is the second world snapshot, with all the chunks reported in the crashlog highlighted.

I'm not sure if this is directly related to terralith, but this appears to be the only spot on the map that I've seen crash like this. I had a previous world with this pack including surveyor and antique atlas 4 and ran into no issues of this kind.

**Comment by HotelCalifornia** [comment]
I'm not worried about sensitive information being revealed here because I'm running this server in a docker container on a VM, but if it helps I can post the logs to mclogs instead

**Comment by sleepingdragoninn** [comment]
Now this is strange, because terralith doesn't add any blocks. Getting a palette crash without changing dimensions and on a fresh world might be a very useful reproduction case though, I'm just not sure exactly how to reproduce it

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/user-attachments/assets/bb2aee3f-8875-4632-8a84-27ebb604be41)

(the amethyst rainforest biome itself is just fine, for the record - it even correctly renders as a jungle on-map)

**Comment by sleepingdragoninn** [comment]
after a lot of pain failing to reproduce this in other ways i'm going to try jam your world on my server and see if it works. 

mclogs from op:

https://mclo.gs/jHW4TzN

https://mclo.gs/DwalEw5

**Comment by sleepingdragoninn** [comment]
tried snapshot 2, didn't manage to get the crash - I'll try snapshot 1. I can't see specific chunks referenced in the crash reports, where are they?

**Comment by sleepingdragoninn** [comment]
![image](https://github.com/user-attachments/assets/f6184499-562a-44be-ad9b-92fde6a7ccc0)

found em, no crash :pensive:

**Comment by sleepingdragoninn** [comment]
full latest.log for crashless run (snapshot 1): 

https://mclo.gs/whdXPIa

full latest.log for crashless run (snapshot 2):

https://mclo.gs/FAv3eV2

@HotelCalifornia does the problem still happen for you?

**Comment by HotelCalifornia** [comment]
Sorry for the late response. It was pretty reliably reproducing with that world specifically, but I've since generated a number of other worlds and haven't seen it come up again on any of those. I'm willing to close this as a strange one-off heisenbug for now but if I run into it again with anything else I'll be sure to come back here. Thanks for your help!

**Comment by HotelCalifornia** [comment]
(oh, and if you don't feel it's appropriate to close at this point, obviously feel free to reopen 😅)

**Comment by HotelCalifornia** [comment]
okayyy just kidding i am back with the same issue on a different world!

[server crash report](https://github.com/user-attachments/files/17781872/crash-2024-11-15_22.09.22-server.txt)
[world zip](https://mega.nz/file/JkNHWAyT#jZEZotOToaVmIIhaSUREwN-lWf7anjbzcUdbyQ0ZQl0)

it might be worth noting that i'm running all this on forge through the forgified fabric api and connector. if you're not seeing the crash locally on a purely fabric server, maybe that's the missing link?

i'm not sure what specific chunks are at issue here this time, but i can do some more digging

**Comment by sleepingdragoninn** [comment]
as far as we're aware, this issue occurs purely on forge 1.20.1, only happens in dedicated servers, and it tends to disappear at random

**Comment by HotelCalifornia** [comment]
ahaa that would explain it then. not a surveyor-specific problem. thank yous!

**Comment by sleepingdragoninn** [comment]
nah I think you've got me wrong, we're *still* hunting for a reliable reproduction case because people are still reporting this happening totally randomly and because it fixes itself nobody has ever managed to get something that causes the crash on our machine.

Forge is an official platform for Surveyor, so it gets full support, even through connector. If you find something that looks like a repro case we want to see what you can make of it

**Comment by HotelCalifornia** [comment]
aha okay! sorry, i'm used to the professional world where there's a lot of, uh, willingness to pass off responsibility for a bug to another team to improve metrics ^^:

i've been feeling pretty icky recently but i'll see if i can dig into that world again at some point soon and see what i can figure out
