### ISSUE TITLE
Why the structure isn't explored

### ISSUE THREAD

**Issue by SettingDust** [sleepingdragoninn/surveyor#54]
0.6.25+1.20 fabric 
![图片](https://github.com/user-attachments/assets/2ef1874a-5e0e-44f0-b293-faff8434cd12)
![图片](https://github.com/user-attachments/assets/5213cb9d-797e-4ab1-bc69-85800d0b5b01)

**Comment by SettingDust** [comment]
Enable in the config file is working. How can I use the `DYNAMIC` with a client side add-on? Do I have to enable it in config file for working?

**Comment by sleepingdragoninn** [comment]
if you aren't using antique atlas or another mod that requires structure discovery, you'll need to set that option to ENABLED.

**Comment by SettingDust** [comment]
> if you aren't using antique atlas or another mod that requires structure discovery, you'll need to set that option to ENABLED.

I'm creating my own add-on mod that is client side

**Comment by SettingDust** [comment]
https://github.com/sisby-folk/antique-atlas/blob/1.20/src/main/java/folk/sisby/antique_atlas/AntiqueAtlas.java#L54-L56 is working

**Comment by SettingDust** [comment]
https://modrinth.com/mod/surveyor-atlases
https://legacy.curseforge.com/minecraft/mc-mods/surveyor-atlases

published XD @sisby-folk
